const express = require('express')
const viewEngine = require('./config/viewEngine')
const bodyParser = require('body-parser')
const initWebRoutes = require('./routes')
const configViewEngine = require('./config/viewEngine')
const connect = require('./config/connectDB')
require('dotenv').config()
let app = express()
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: true }))
viewEngine(app)
connect()
initWebRoutes(app)
app.listen(3000, () => {
    console.log('listening in port 3000')
})